"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var division_1 = require("./division");
var multiplication_1 = require("./multiplication");
var addition_1 = require("./addition");
var subtraction_1 = require("./subtraction");
console.log("The division of 24 and 6 is: ".concat((0, division_1.division)(24, 6)));
console.log("The multiplication of 24 and 6 is:".concat((0, multiplication_1.multiplication)(24, 6)));
console.log("The addition of 24 and 6 is:".concat((0, addition_1.addition)(24, 6)));
console.log("The subtraction of 24 and 6 is:".concat((0, subtraction_1.subtraction)(24, 6)));
